# Global settings applied to the whole site.
#
# “publish” is the directory to publish (relative to root of your repo),
# “command” is your build command,
build:
  publish: public
  command: npm run build

context:
  # Deploy Preview context: All Deploy Previews
  # will inherit these settings.
  deploy-preview:
    command: npm run build
    environment:
      BUILD_ENV: development
  # Branch context: All deploys to this branch
  # will inherit these settings.
  branch-deploy:
    command: npm run build
    environment:
      BUILD_ENV: development
  # Production context: All deploys to the main
  # repository branch will inherit these settings.
  production:
    environment:
      BUILD_ENV: production
template:
  environment:
    CONTENTFUL_ORGANIZATION_ID: Enter your contentful organization id
    CONTENTFUL_MANAGEMENT_TOKEN: Enter your contentful management token
# redirects:
#   - from: 'https://hinterland.dev/*'
#     to: 'https://hinterland.software/'
#     status: 301
#     force: true
